DROP TABLE IF EXISTS fact_sales CASCADE;
DROP TABLE IF EXISTS dim_pet CASCADE;
DROP TABLE IF EXISTS dim_product CASCADE;
DROP TABLE IF EXISTS dim_seller CASCADE;
DROP TABLE IF EXISTS dim_customer CASCADE;
DROP TABLE IF EXISTS dim_store CASCADE;
DROP TABLE IF EXISTS dim_supplier CASCADE;
DROP TABLE IF EXISTS dim_brand CASCADE;
DROP TABLE IF EXISTS dim_pet_category CASCADE;
DROP TABLE IF EXISTS dim_product_category CASCADE;
DROP TABLE IF EXISTS dim_pet_type CASCADE;
DROP TABLE IF EXISTS dim_city CASCADE;
DROP TABLE IF EXISTS dim_country CASCADE;

CREATE TABLE dim_country (
    country_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_name TEXT NOT NULL UNIQUE
);

CREATE TABLE dim_city (
    city_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_name TEXT NOT NULL,
    country_key INTEGER REFERENCES dim_country(country_key),
    CONSTRAINT uq_dim_city UNIQUE (city_name, country_key)
);

CREATE TABLE dim_pet_type (
    pet_type_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_type_name TEXT NOT NULL UNIQUE
);

CREATE TABLE dim_product_category (
    product_category_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_category_name TEXT NOT NULL UNIQUE
);

CREATE TABLE dim_pet_category (
    pet_category_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_category_name TEXT NOT NULL UNIQUE
);

CREATE TABLE dim_brand (
    brand_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_name TEXT NOT NULL UNIQUE
);

CREATE TABLE dim_supplier (
    supplier_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_natural_key CHAR(32) NOT NULL UNIQUE,
    supplier_name TEXT NOT NULL,
    supplier_contact TEXT,
    supplier_email TEXT,
    supplier_phone TEXT,
    supplier_address TEXT,
    supplier_city_key INTEGER REFERENCES dim_city(city_key),
    supplier_country_key INTEGER REFERENCES dim_country(country_key)
);

CREATE TABLE dim_store (
    store_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_natural_key CHAR(32) NOT NULL UNIQUE,
    store_name TEXT NOT NULL,
    store_location TEXT,
    store_city_key INTEGER REFERENCES dim_city(city_key),
    store_state TEXT,
    store_country_key INTEGER REFERENCES dim_country(country_key),
    store_phone TEXT,
    store_email TEXT
);

CREATE TABLE dim_customer (
    customer_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_natural_key CHAR(32) NOT NULL UNIQUE,
    source_customer_id INTEGER,
    customer_first_name TEXT,
    customer_last_name TEXT,
    customer_email TEXT,
    customer_age INTEGER,
    customer_country_key INTEGER REFERENCES dim_country(country_key),
    customer_postal_code TEXT
);

CREATE TABLE dim_seller (
    seller_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_natural_key CHAR(32) NOT NULL UNIQUE,
    source_seller_id INTEGER,
    seller_first_name TEXT,
    seller_last_name TEXT,
    seller_email TEXT,
    seller_country_key INTEGER REFERENCES dim_country(country_key),
    seller_postal_code TEXT,
    store_key INTEGER REFERENCES dim_store(store_key)
);

CREATE TABLE dim_product (
    product_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_natural_key CHAR(32) NOT NULL UNIQUE,
    source_product_id INTEGER,
    product_name TEXT NOT NULL,
    product_category_key INTEGER REFERENCES dim_product_category(product_category_key),
    pet_category_key INTEGER REFERENCES dim_pet_category(pet_category_key),
    brand_key INTEGER REFERENCES dim_brand(brand_key),
    supplier_key INTEGER REFERENCES dim_supplier(supplier_key),
    product_price NUMERIC(12,2),
    product_quantity INTEGER,
    product_weight NUMERIC(12,2),
    product_color TEXT,
    product_size TEXT,
    product_material TEXT,
    product_description TEXT,
    product_rating NUMERIC(3,1),
    product_reviews INTEGER,
    product_release_date DATE,
    product_expiry_date DATE
);

CREATE TABLE dim_pet (
    pet_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_natural_key CHAR(32) NOT NULL UNIQUE,
    pet_name TEXT,
    pet_type_key INTEGER REFERENCES dim_pet_type(pet_type_key),
    pet_breed TEXT,
    customer_key INTEGER REFERENCES dim_customer(customer_key)
);

CREATE TABLE fact_sales (
    sale_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_row_id BIGINT NOT NULL UNIQUE REFERENCES mock_data(source_row_id),
    source_sale_id INTEGER,
    sale_date DATE,
    customer_key INTEGER REFERENCES dim_customer(customer_key),
    seller_key INTEGER REFERENCES dim_seller(seller_key),
    product_key INTEGER REFERENCES dim_product(product_key),
    store_key INTEGER REFERENCES dim_store(store_key),
    pet_key INTEGER REFERENCES dim_pet(pet_key),
    sale_quantity INTEGER,
    sale_total_price NUMERIC(12,2),
    sale_unit_price NUMERIC(12,2),
    loaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_fact_sales_sale_date ON fact_sales(sale_date);
CREATE INDEX idx_fact_sales_customer ON fact_sales(customer_key);
CREATE INDEX idx_fact_sales_product ON fact_sales(product_key);
CREATE INDEX idx_fact_sales_store ON fact_sales(store_key);
CREATE INDEX idx_fact_sales_seller ON fact_sales(seller_key);
CREATE INDEX idx_fact_sales_pet ON fact_sales(pet_key);
